### ISSUE TITLE
简码设置讨论

### ISSUE THREAD

**Issue by forFudan** [forFudan/yuhao#20]
此议题用于讨论一、二、三级简码字词的设置和调整。凡建议改动的，可以标注原因，如：单字频率、手感、简字词联合频率等等。请不要使用“我觉得这个字使用率更高”之类的语句。

**Comment by orbitoo** [comment]
「眞」(rmx), 「真」之舊字形.

**Comment by forFudan** [comment]
> 「眞」(rmx), 「真」之舊字形.

在兩個繁體的方案裏設置完成。
