### ISSUE TITLE
基於拆分表做一套簡碼是否違反 LICENSE

### ISSUE THREAD

**Issue by ywxt** [forFudan/yuhao#41]
>「如果您再混合、转换、或者基于该作品创作，您不可以分发修改作品，除非您得到作者的许可。」

請問自定義簡碼碼表是否屬於「再混合、转换、或者基于该作品创作」，需不需要得到作者的許可？

**Comment by forFudan** [comment]
没问题的！

**Comment by ywxt** [comment]
感謝回覆！
