### ISSUE TITLE
拆分表请添加UTF16编码，部分汉字笔画乱码

### ISSUE THREAD

**Issue by lenny20** [forFudan/yuhao#42]
1、建议给拆分表添加UTF16统一编码，以便准确查询，尤其有简化方案变化。
2、没有字体的话会显示空白，但这表中有些笔画都是黑底问号。我改就因GBK编码丢失更多汉字。
谢谢！

**Comment by forFudan** [comment]
> 1、建议给拆分表添加UTF16统一编码，以便准确查询，尤其有简化方案变化。 2、没有字体的话会显示空白，但这表中有些笔画都是黑底问号。我改就因GBK编码丢失更多汉字。 谢谢！

这次的 v3.4.3 版本在第三重的注解中加入了该字的 Unicode 编码。我把这个 issue 重新打开了。

[https://github.com/forFudan/yuhao/releases/tag/v3.4.3-beta](https://github.com/forFudan/yuhao/releases/tag/v3.4.3-beta)

如果没问题再关闭它哈。
