### ISSUE TITLE
install.md

### ISSUE THREAD

**Issue by Dieken** [forFudan/yuhao#43]
install.md 这个 "`"  大概要用 \ 转义，目前在官网显示不出来。

```
输入过程中，按下 ` 符号作为分隔，使用**数字键或空格键**依次选择单字，即可实现精确造词。

```

**Comment by forFudan** [comment]
确实是，这个地方得转义一下，否则就是引导verbatim了。

**Comment by forFudan** [comment]
突然意识到：这个不是官网仓库，这个是方案仓库。官网的仓库是 yu

**Comment by Dieken** [comment]
这个仓库里也有个 install.md 😅

forFudan/yu/ 里改叫 「Grave 符号」。。。还不如叫「反引号」呢😂

**Comment by forFudan** [comment]
确实，你说得对，我改一下。
