### ISSUE TITLE
宇浩星陈v3.6.0中: 夜(亠亻夕乀)的拆分原理, 为何不是:亠亻夂乀

### ISSUE THREAD

**Issue by lets2zg** [forFudan/yuhao#48]
宇浩星陈v3.6.0中: 夜(亠亻夕乀)的拆分原理, 为何不是:亠亻夂乀

**Comment by forFudan** [comment]
> 宇浩星陈v3.6.0中: 夜(亠亻夕乀)的拆分原理, 为何不是:亠亻夂乀

@lets2zg 因爲這個字就是按照「亠亻夕乀」寫的。如果你的筆順是「亠亻夂乀」説明寫錯了。:D
